cmo_customer_invoice_report/models/account.py, cmo_customer_invoice_report/report/cmo_purchase_daybook.jrxml, cmo_customer_invoice_report/report/report_data.xml, cmo_hr_expense_report/models/hr.py, cmo_hr_expense_report/report/cmo_hr_clearing.jrxml, cmo_hr_expense_report/report/cmo_hr_pettycash.jrxml, cmo_hr_expense_report/report/report_data.xml
=> [ADD] clearing, pettycash and purchase book day

cmo_customer_invoice_report/models/account.py, cmo_customer_invoice_report/report/cmo_customer_invoice.jrxml, cmo_customer_invoice_report/report/cmo_customer_invoice2.jrxml, cmo_customer_invoice_report/report/cmo_customer_payment.jrxml, cmo_customer_invoice_report/report/cmo_journal_voucher.jrxml, cmo_customer_invoice_report/report/cmo_receipt_voucher.jrxml, cmo_customer_invoice_report/report/cmo_sale_voucher.jrxml, cmo_customer_invoice_report/report/report_data.xml
=> [ADD] sale receipt voucher report

cmo_hr/views/hr_view.xml, cmo_hr_level_validation/models/hr_level_validation.py, cmo_level_validation/models/level_validation.py, cmo_level_validation/views/level_validation_view.xml
=> [IMP] pettycash approval

cmo_payment_receipt_intransit_xls/report/payment_receipt_intransit_report_xls.py, cmo_payment_receipt_intransit_xls/wizard/wiz_payment_receipt_intransit_report.xml
=> [IMP] adjust intransit report

cmo_cost_control_sheet/report/cost_control_sheet_report_xls.py, cmo_project/models/__init__.py, cmo_project/models/project.py, cmo_project/models/project_adjustment.py, cmo_project/views/project_view.xml, cmo_project/wizard/close_reason.py
=> [IMP] project adjustment cost control sheet

account_asset_management_enhanced/models/account_asset_profile.py, account_asset_management_enhanced/views/account_asset_profile_view.xml
=> [IMP] fields number sequence

cmo_sale/models/sale.py
=> [IMP] close order line constrain

cmo_purchase_invoice_plan/__openerp__.py, cmo_purchase_invoice_plan/views/purchase_view.xml
=> [IMP] Show create invoices button in state confirmed only!

cmo_customer_invoice_report/report/cmo_purchase_daybook.jrxml
P'Nuii Please merge krub
ref issue >> http://128.199.123.133:10083/issues/862
=> [IMP] Adjust Purchase Day Book Report

cmo_account_move_adjustment/__init__.py, cmo_account_move_adjustment/__openerp__.py, cmo_account_move_adjustment/models/__init__.py, cmo_account_move_adjustment/models/account.py, cmo_account_move_adjustment/models/account_invoice.py, cmo_account_move_adjustment/views/account_invoice_view.xml, cmo_account_move_adjustment/wizards/__init__.py, cmo_account_move_adjustment/wizards/create_journal_entry_wizard.py, cmo_account_move_adjustment/wizards/create_journal_entry_wizard.xml
Ref issue >> http://128.199.123.133:10083/issues/904
=> [ADD] Add cmo_account_move_adjustment

cmo_account_move_adjustment/__init__.py, cmo_account_move_adjustment/models/__init__.py
=> [IMP] Change order loading data

cmo_account/data/report_data.xml, cmo_account/report/cmo_withholding_cert.jrxml, cmo_account/wizard/print_wht_cert_wizard.py
P'Nuii please merge.
Ref issue >> http://128.199.123.133:10083/issues/906
=> [IMP] Adjust WHT Cert Form

cmo_purchase/views/purchase_view.xml
Ref issue >> http://128.199.123.133:10083/issues/915
=> [IMP] qo domain not cancel

cmo_account/report/cmo_withholding_cert.jrxml
Ref issue >> http://128.199.123.133:10083/issues/906
=> [IMP] Add rate in WHT Cert Form

cmo_cost_control_sheet/report/cost_control_sheet_report_xls.py, cmo_cost_control_sheet/wizard/wiz_cost_control_sheet_report.py, cmo_cost_control_sheet/wizard/wiz_cost_control_sheet_report.xml
Ref issues >> 
http://128.199.123.133:10083/issues/916
http://128.199.123.133:10083/issues/919
=> [IMP] Adjust Report

cmo_account_move_adjustment/views/account_invoice_view.xml
Ref issue >> http://128.199.123.133:10083/issues/924
Related >> https://github.com/ecosoft-odoo/cmo_generic/pull/10
=> [IMP] Add smart button

cmo_account/report/cmo_withholding_cert.jrxml
Ref issue >> http://128.199.123.133:10083/issues/931
=> [IMP] Adjust signature date

cmo_account/report/cmo_withholding_cert.jrxml
Ref issue >> http://128.199.123.133:10083/issues/931
=> [IMP] Adjust Date Format

cmo_project/views/project_view.xml
Ref issue >> http://128.199.123.133:10083/issues/933
=> [IMP] Require additional field

cmo_account_cancel_voucher_reason/__init__.py, cmo_account_cancel_voucher_reason/__openerp__.py, cmo_account_cancel_voucher_reason/wizards/__init__.py, cmo_account_cancel_voucher_reason/wizards/cancel_reason.py
P'Nuii pleasee review krub.
Rerated PR >> https://github.com/ecosoft-odoo/cmo_generic/pull/14
Ref issue >> http://128.199.123.133:10083/issues/938
=> [IMP] Check cancel voucher

cmo_customer_invoice_report/report/cmo_customer_payment.jrxml
Ref issue >> http://128.199.123.133:10083/issues/936
=> [IMP] Adjust invoice amount

cmo_account/models/account.py, cmo_account/views/account_view.xml
Ref issue >> http://128.199.123.133:10083/issues/932
=> [IMP] Add search voucher number cheque

cmo_customer_invoice_report/report/cmo_customer_payment.jrxml
Ref issue >> http://128.199.123.133:10083/issues/936
=> [IMP] Adjust amount text and decimal vat to 2 digits

cmo_purchase/models/purchase.py
Ref issue >> http://128.199.123.133:10083/issues/949
=> [IMP] Change text sale_order_line_ref

cmo_purchase/models/product.py, cmo_purchase/models/purchase.py, cmo_purchase/models/sale.py, cmo_purchase/views/purchase_view.xml
Ref issue >> http://128.199.123.133:10083/issues/898
=> [IMP] Add multi-selection internal category in po type

cmo_project/models/project.py, cmo_project/wizard/close_reason.py
p'nuii please merge krub.
Ref issue >> http://128.199.123.133:10083/issues/957
=> [IMP] Pull lost by from project competitor

cmo_purchase/models/sale.py
=> [IMP] Change SaleOrderLine to SaleLayoutCategory

cmo_account/models/account_voucher.py, cmo_account/views/account_voucher_view.xml, cmo_customer_invoice_report/report/cmo_supplier_payment_cheque.jrxml
Ref issue >> http://128.199.123.133:10083/issues/937
=> [IMP] Add payee for print out cheque

cmo_customer_invoice_report/report/cmo_supplier_payment_voucher.jrxml
P'Nuii please merge krub
Ref issue >> http://128.199.123.133:10083/issues/937
=> [IMP] Change value paid to payee

cmo_project/models/project.py
Ref issue >> http://128.199.123.133:10083/issues/957
=> [IMP] Change _rec_name project competitor by company

cmo_project/views/project_view.xml
Ref issue >> http://128.199.123.133:10083/issues/965
=> [IMP] Change 'Reference' to 'Project number' on Project List view

cmo_account/views/account_voucher_view.xml
=> [IMP] Change XML ID Voucher Payment

cmo_hr/__openerp__.py, cmo_hr/views/hr_view.xml
Ref issue >> http://128.199.123.133:10083/issues/958
=> [IMP] Default and readonly pay type in expense

cmo_customer_invoice_report/models/account.py, cmo_customer_invoice_report/report/cmo_sale_daybook.jrxml, cmo_customer_invoice_report/report/report_data.xml
Ref issue >> http://128.199.123.133:10083/issues/964
=> [IMP] Adjust Sale Day Book Report

cmo_account/models/account_voucher.py, cmo_account/views/account_voucher_view.xml, cmo_customer_invoice_report/report/cmo_receipt_voucher.jrxml
Ref issue >> http://128.199.123.133:10083/issues/968
=> [IMP] Merge journal items and seperate by comma

cmo_account_supplier_billing/__init__.py, cmo_account_supplier_billing/__openerp__.py, cmo_account_supplier_billing/models/__init__.py, cmo_account_supplier_billing/models/account_voucher.py, cmo_account_supplier_billing/models/supplier_billing.py, cmo_account_supplier_billing/views/supplier_billing.xml
Ref issue >> http://128.199.123.133:10083/issues/966
=> [ADD] Add cmo_account_supplier_billing

cmo_hr/__openerp__.py, cmo_hr/models/__init__.py, cmo_hr/models/analytic.py, cmo_hr/views/hr_view.xml, cmo_purchase/models/purchase.py
Ref issue >> http://128.199.123.133:10083/issues/959
=> [IMP] Add domain project on purchase and expense line

cmo_project/models/project.py, cmo_project/security/ir.model.access.csv
Ref issue >> http://128.199.123.133:10083/issues/973
=> [IMP] Change right user readonly

account_asset_management_enhanced/models/account_asset_profile.py, cmo_project/models/project.py
Ref issue >> http://128.199.123.133:10083/issues/977
=> [IMP] Adjust Asset Profiles

cmo_hr/views/hr_view.xml
Ref issue >> http://128.199.123.133:10083/issues/992
=> [IMP] Pettycash default payment by is cash

cmo_account/views/account_voucher_view.xml
Ref issue >> http://128.199.123.133:10083/issues/988
=> [IMP] Add Date Value in Tree View Voucher

cmo_customer_invoice_report/report/cmo_supplier_payment_voucher.jrxml
Ref issue >> http://128.199.123.133:10083/issues/987
=> [IMP] Lose Description

cmo_account/views/account_voucher_view.xml, cmo_customer_invoice_report/report/report_data.xml
Ref issue >> http://128.199.123.133:10083/issues/989
http://128.199.123.133:10083/issues/993
=> [IMP] Add move_id in voucher

cmo_hr/models/hr.py
Ref issue >> http://128.199.123.133:10083/issues/992
=> [IMP] Change selection payment by

cmo_hr_expense_report/report/cmo_hr_clearing.jrxml
Ref issue >> http://128.199.123.133:10083/issues/980
=> [IMP] Adjust Employee Clearing Form

cmo_purchase/models/purchase.py
Ref issue >> http://128.199.123.133:10083/issues/1004
=> [IMP] Add domain PO Approve

cmo_operating_unit/__init__.py, cmo_operating_unit/__openerp__.py, cmo_operating_unit/models/__init__.py, cmo_operating_unit/models/operating_unit.py, cmo_operating_unit/views/operating_unit_view.xml, cmo_stock/__openerp__.py, cmo_stock/models/res_partner.py, cmo_stock/views/stock_view.xml
Ref issue >> http://128.199.123.133:10083/issues/1003
=> [IMP] Adjust domain partner_id

cmo_stock/models/res_partner.py, cmo_stock/views/stock_view.xml
Ref issue >> http://128.199.123.133:10083/issues/1003
=> [IMP] Check domain partner on stock picking for only internal move

cmo_hr_expense_report/report/cmo_hr_clearing.jrxml, cmo_hr_expense_report/report/cmo_hr_pettycash.jrxml, cmo_hr_expense_report/report/report_data.xml
Ref issue >> http://128.199.123.133:10083/issues/978
http://128.199.123.133:10083/issues/1007
=> [IMP] Adjust Expense Report

cmo_customer_invoice_report/report/cmo_receipt_voucher.jrxml, cmo_customer_invoice_report/report/cmo_sale_daybook.jrxml
Ref issue >> http://128.199.123.133:10083/issues/1011
=> [IMP] Change sort to valiable debit and credit in type double

cmo_customer_invoice_report/models/account.py, cmo_customer_invoice_report/report/cmo_receipt_tax_invoice_peo.jrxml, cmo_customer_invoice_report/report/report_data.xml
Ref issue >> http://128.199.123.133:10083/issues/984
=> [IMP] Add Receipt/Tax Invoice (PEO)

cmo_customer_invoice_report/report/cmo_receipt_tax_invoice_peo.jrxml
Ref issue >> http://128.199.123.133:10083/issues/984
=> [IMP] Change date and ref number payment

cmo_customer_invoice_report/models/account.py, cmo_customer_invoice_report/report/cmo_receipt.jrxml, cmo_customer_invoice_report/report/report_data.xml
Ref issue >> http://128.199.123.133:10083/issues/983
=> [IMP] Add Receipt Form

cmo_customer_invoice_report/report/cmo_customer_invoice2.jrxml, cmo_project/models/account_invoice.py, cmo_project/views/account_view.xml, cmo_sale/views/account_view.xml
Ref issue >> http://128.199.123.133:10083/issues/1006
=>  [IMP] Create function get invoice project data

cmo_customer_invoice_report/report/cmo_supplier_payment_voucher.jrxml
=> [IMP] Change valiable sort type of supplier payment voucher

cmo_customer_invoice_report/__openerp__.py, cmo_customer_invoice_report/models/account.py, cmo_customer_invoice_report/report/cmo_customer_invoice2.jrxml, cmo_customer_invoice_report/report/cmo_customer_payment.jrxml, cmo_customer_invoice_report/report/report_data.xml
Ref issue >> http://128.199.123.133:10083/issues/982
Ref PR >> https://github.com/ecosoft-odoo/cmo_generic/pull/22
=> [IMP] Add multi langauge forms

cmo_customer_invoice_report/report/cmo_customer_invoice.jrxml, cmo_customer_invoice_report/report/cmo_receipt.jrxml, cmo_customer_invoice_report/report/cmo_receipt_voucher.jrxml, cmo_customer_invoice_report/report/report_data.xml, cmo_sale_report/__openerp__.py, cmo_sale_report/models/__init__.py, cmo_sale_report/models/sale.py
http://128.199.123.133:10083/issues/1016
http://128.199.123.133:10083/issues/1010
http://128.199.123.133:10083/issues/1014
=> [IMP] Adjust Receipt Voucher

cmo_customer_invoice_report/report/cmo_journal_voucher.jrxml, cmo_customer_invoice_report/report/cmo_purchase_daybook.jrxml, cmo_customer_invoice_report/report/cmo_receipt_voucher.jrxml, cmo_customer_invoice_report/report/cmo_sale_daybook.jrxml, cmo_customer_invoice_report/report/cmo_supplier_payment_voucher.jrxml
Ref issue >> http://128.199.123.133:10083/issues/962
=> [IMP] Adjust multiple voucher in same report

cmo_account/models/account_invoice.py
=> [IMP] Remove state readonly invoice line out

cmo_project/views/project_view.xml
Ref issue >> http://128.199.123.133:10083/issues/1034
=> [IMP] Move project status position in list view

cmo_purchase_group/__init__.py, cmo_purchase_group/__openerp__.py, cmo_purchase_group/models/__init__.py, cmo_purchase_group/models/account_invoice.py, cmo_purchase_group/models/common.py, cmo_purchase_group/models/product.py, cmo_purchase_group/models/purchase.py, cmo_purchase_group/models/res_partner.py, cmo_purchase_group/models/stock.py, cmo_purchase_group/security/purchase_security.xml
=> [IMP] Adjust purchase group

cmo_project/views/project_view.xml
Ref issue >> http://128.199.123.133:10083/issues/1035
=> [IMP] Adjust position field in list view

cmo_cost_control_sheet/__openerp__.py, cmo_cost_control_sheet/views/project_view.xml, cmo_cost_control_sheet/wizard/wiz_cost_control_sheet_report.xml, cmo_project/models/project.py
Ref issue >> http://128.199.123.133:10083/issues/1038
=> [IMP] Adjust cost control sheet

cmo_account/models/account_voucher.py
Objective
Set default Company Bank Account when payment_type is cheque and cheque_cash
http://128.199.123.133:10083/issues/960
=> [IMP] Add change default = 1 (Payment Type)

account_asset_depreciation_xls/wizard/wiz_account_asset_report.xml
Ref issue >> http://128.199.123.133:10083/issues/1042
=> [IMP] Remove special out from domain period

cmo_purchase/models/sale.py
=> [IMP] adjust domain sale_order_line_ref_id

cmo_project/views/project_view.xml
Ref issue >> http://128.199.123.133:10083/issues/1053
=> [IMP] Add group by state

cmo_project/views/project_view.xml
http://128.199.123.133:10083/issues/1054
=> [IMP] Adjust filter state completed

cmo_project/views/project_view.xml
Ref issue >> http://128.199.123.133:10083/issues/1058
=> [IMP] Adjust Filter Project

cmo_account/report/withholding_cert.jrxml
=> [IMP] Adjust WHT Form

cmo_hr_expense_report/report/cmo_hr_clearing.jrxml
=> [IMP] Adjust clearing form

cmo_sale_report/report/cmo_sale_order.jrxml
Ref issue >> http://128.199.123.133:10083/issues/1073
=> [IMP] Adjust quotation form

cmo_account/views/account_bank_receipt_view.xml
p'nuii please merge krub.
Ref issue >> http://128.199.123.133:10083/issues/932
=> [IMP] Change external id of view account move line of bank receipt

cmo_account/models/account.py
=> [IMP] Adjust post journal entry

cmo_hr/views/hr_view.xml
=> [IMP] Required field product

cmo_purchase/views/purchase_view.xml
=> [IMP] Add required product in purchase order line

cmo_sale/views/sale_view.xml
=> add field and search by quotation number 

cmo_cost_control_sheet/report/cost_control_sheet_report_xls.py
This issue is cost control sheet report
Ref issue >> http://128.199.123.133:10083/issues/1412
=> [IMP] Add subtotal and section expense

cmo_cost_control_sheet/report/cost_control_sheet_report_xls.py
This issue is cost control sheet report
=> [IMP] Filter price as in contract or estimate cost != 0

cmo_operating_unit/models/account_voucher.py
http://128.199.123.133:10083/issues/1508
=> [ENH] cmo_operating_unit, cover case payment for mixed OU invoices

cmo_cost_control_sheet/report/cost_control_sheet_report_xls.py
issue http://128.199.123.133:10083/issues/1412
=> [IMP] Adjust cost control sheet report

cmo_cost_control_sheet/report/cost_control_sheet_report_xls.py
http://128.199.123.133:10083/issues/1412
=> [IMP] Add export by

account_trial_balance_report/__openerp__.py, account_trial_balance_report/models/trial_balance_report.py, account_trial_balance_report/security/ir.model.access.csv, account_trial_balance_report/views/account_view.xml
ผมมีการเพิ่ม account_move_line_view ไว้สำหรับ drilldown trial balance line เพื่อให้ได้ record ที่ถูกต้อง
สาเหตุที่เพิ่มเพราะว่าเมื่อ click ปุ่ม open items ไม่ได้เป็นสิทธิ์เดียวกับ admin (ถึงแม้จะใส่ sudo แล้วก็ตาม) ทำให้เวลา search view account.move.line ถูก domain ของ record rule ทับว่าต้องแสดงแค่ OU ที่ user นั้นมีสิทธิ์เท่านั้น ทำให้ยอด amount ตอน drilldown ไม่เท่ากับ ยอด amount ใน trial balance line
=> [IMP] Report not show OU inactive

account_trial_balance_report/models/trial_balance_report.py
p'nuii please review krub (Trial Balance (web) report)
เพิ่ม กรอง initial move และ focus move ด้วย fiscalyear
http://128.199.123.133:10083/issues/1546
=> [IMP] Add filter fiscalyear in domain init_move and focus_move

cmo_report_balance_sheet_xls/report/balance_sheet_xls.py, cmo_report_balance_sheet_xls/wizard/balance_sheet_wizard_view.xml
P'nuii please review krub
Ref issue >> http://128.199.123.133:10083/issues/1529
=> [IMP] Add active = true in bs and pl report

cmo_cost_control_sheet/report/cost_control_sheet_report_xls.py
issue >> http://128.199.123.133:10083/issues/1412
=> [IMP] Adjust section adjustment project

cmo_hr_expense_report/models/hr.py
issue >> http://128.199.123.133:10083/issues/1577
issue นี้ผม hide print button จากการดู AV/EX ในหน้า project ครับ รบกวนพี่หนุ่ยรีวิวหน่อย
=> [IMP] hide menu print from active model is project.project

account_asset_management_enhanced/models/account_move.py, cmo_cost_control_sheet/report/cost_control_sheet_report_xls.py
http://128.199.123.133:10083/issues/1412
http://128.199.123.133:10083/issues/1586
=> [IMP] Fix bug cmo

cmo_cost_control_sheet/report/cost_control_sheet_report_xls.py, cmo_project/models/project.py
issue: 
http://128.199.123.133:10083/issues/1583
http://128.199.123.133:10083/issues/1412
=> [IMP] Add state waiting validate to compute expense

cmo_hr_expense_report/report/cmo_hr_expense.jrxml
=> [FIX] Fix Expense Report

cmo_cost_control_sheet/report/cost_control_sheet_report_xls.py
=> [FIX] Change custom_group to custom_groups

cmo_sale/models/product.py
=> [Fix] can not save quotation

cmo_sale/models/product.py
=> [FIX] can not save quoation

cmo_sale_discount_total_enhance/models/sale.py
พี่หนุ่ยช่วย check หน่อยครับ ว่าแก้ไขจุดนี้ถูกต้องหรือป่าว
ผม test แล้วได้ค่าตรงแล้วครับ
[T0021] Support-CMO: Quotation discount เลข amount ไม่ตรงตามที่กรอกข้อมูล
=> [FIX] Discount is wrong

cmo_project/models/project.py, cmo_project/views/project_view.xml
=> [IMP] Add Invoice Open and Invoice Paid

cmo_sale_report/report/cmo_sale_order.jrxml
=> [IMP] Add sort custom group

cmo_project/__openerp__.py, cmo_project/models/project.py, cmo_project/views/project_view.xml, cmo_project/wizard/__init__.py, cmo_project/wizard/change_close_project.py, cmo_project/wizard/change_close_project_view.xml
=> [IMP] Add Close Project By Accounting

cmo_hr/models/analytic.py, cmo_purchase/models/purchase.py, cmo_sale/models/sale.py
=> [IMP] Adjust domain of project

cmo_hr_level_validation/models/hr_level_validation.py, cmo_hr_level_validation/views/hr_level_validation_view.xml
=> [IMP] Add hide_confirm_button

cmo_hr_level_validation/models/hr_level_validation.py, cmo_hr_level_validation/views/hr_level_validation_view.xml
=> [IMP] Hide Validate and Refuse for internal audit group

cmo_sale_discount_total_enhance/models/sale.py
=> [FIX] Fix amount total != amount untaxed + amount tax

cmo_sale_report/report/cmo_sale_order.jrxml
=> [IMP] Add size text box of customer in summary section

cmo_customer_invoice_report/models/account.py, cmo_customer_invoice_report/report/cmo_customer_invoice.jrxml, cmo_customer_invoice_report/report/report_data.xml
=> [IMP] Add Invoice (PEO EN)

cmo_sale_report/report/cmo_sale_order.jrxml
=> [IMP] Add isStretchWithOverflow=true

cmo_sale_report/report/cmo_sale_order.jrxml
=> [IMP] Add height size of summary band and convenant

cmo_hr_level_validation/models/hr_level_validation.py, cmo_hr_level_validation/views/hr_level_validation_view.xml
=> [IMP] Remove field hide_button

cmo_project/models/project.py
=> [IMP] Add copy=False in field close_project

cmo_sale_report/report/cmo_sale_order.jrxml
=> [IMP] Change variable type to number

cmo_hr_level_validation/models/hr_level_validation.py, cmo_hr_level_validation/wizard/__init__.py, cmo_hr_level_validation/wizard/cancel_reason.py, cmo_purchase_level_validation/__init__.py, cmo_purchase_level_validation/__openerp__.py, cmo_purchase_level_validation/models/purchase_level_validation.py, cmo_purchase_level_validation/wizard/__init__.py, cmo_purchase_level_validation/wizard/create_invoice.py
=> [IMP] Support #T0056

cmo_customer_invoice_report/models/account.py, cmo_customer_invoice_report/report/cmo_receipt_tax_invoice_peo.jrxml, cmo_customer_invoice_report/report/report_data.xml
=> [ADD] Add Receipt Tax Invoice (PEO EN)

cmo_customer_invoice_report/report/cmo_receipt_tax_invoice_peo.jrxml
=> [IMP] Adjust position of comment field from y=28 to y=13

cmo_cost_control_sheet/report/cost_control_sheet_report_xls.py
=> [FIX] Fix formula of gross_margin

cmo_sale_report/report/cmo_sale_order.jrxml
=> Imp pk fix bug cmo 13 06 2019

cmo_purchase_report/jrxml_reports/cmo_purchase_order.jrxml, cmo_purchase_report/jrxml_reports/cmo_purchase_order_product.jrxml
=> [IMP] Adjust form purchase order

cmo_cost_control_sheet/report/cost_control_sheet_report_xls.py
=> [IMP] Sort quotation

cmo_customer_invoice_report/report/cmo_receipt_tax_invoice_peo.jrxml
=> [IMP] Adjust Receipt/Tax Invoice (PEO) Form

cmo_cost_control_sheet/report/cost_control_sheet_report_xls.py
=> [FIX] Fix bug section management and operation fee duplicate

cmo_sale_report/report/cmo_sale_order.jrxml
=> [IMP] sort data by Group, Custom Group, Section

cmo_customer_invoice_report/report/cmo_receipt_voucher.jrxml, cmo_customer_invoice_report/report/cmo_supplier_payment_voucher.jrxml
=> [IMP] Adjust voucher form

cmo_project/models/project.py, cmo_project/wizard/close_reason.py, cmo_project/wizard/project_search.py
=> [IMP] Remove IT Close Project out from close_reason

cmo_prq/__openerp__.py, cmo_prq/models/purchase_prq.py, cmo_prq/views/purchase_prq_view.xml
=> [IMP] Add approve_permission in cmo_prq

account_asset_management_enhanced/__openerp__.py, account_asset_management_enhanced/models/__init__.py, account_asset_management_enhanced/models/account_asset.py, account_asset_management_enhanced/models/purchase.py
=> [IMP] account_asset_management_enhanced

cmo_async_process/cmo_action_asset_compute/cmo_action_asset_compute.py
=> [IMP] Sort account move number in computing journal number

cmo_project_actual_budget/__init__.py, cmo_project_actual_budget/__openerp__.py, cmo_project_actual_budget/models/__init__.py, cmo_project_actual_budget/models/project.py, cmo_project_actual_budget/models/res_users.py, cmo_project_actual_budget/views/project_view.xml, cmo_project_actual_budget/wizard/__init__.py, cmo_project_actual_budget/wizard/project_search.py, cmo_project_actual_budget/wizard/project_search_view.xml
=> [ADD] cmo_project_actual_budget

cmo_account/models/account.py, cmo_account/models/account_voucher.py, cmo_account/views/account_view.xml, cmo_account/views/account_voucher_view.xml
=> [IMP] Add is_cancel_cheque

cmo_account/models/account.py, cmo_account/models/account_voucher.py, cmo_account/views/account_view.xml, cmo_account/views/account_voucher_view.xml
=> [12.0][IMP] Change is_cancel_cheque to cheque_status

cmo_project/models/project.py, cmo_project/views/project_view.xml
Change topic header in tree view from "Actual Price" => "Actual Price (Quotation)"
=> project_view.xml

cmo_project_actual_budget/models/project.py
=> [FIX] runtime error

cmo_hr/models/__init__.py, cmo_hr/models/hr.py, cmo_hr/views/hr_view.xml
เพิ่ม Field ตาม Requirement
สิ่งที่เพิ่ม
=> [ADD] Start, Probation,End - Date

cmo_async_process/cmo_action_asset_compute/reports/cmo_journal_voucher_group.jrxml, cmo_customer_invoice_report/report/cmo_bank_payment.jrxml, cmo_customer_invoice_report/report/cmo_bank_receipt.jrxml, cmo_customer_invoice_report/report/cmo_journal_voucher.jrxml, cmo_customer_invoice_report/report/cmo_purchase_daybook.jrxml, cmo_customer_invoice_report/report/cmo_receipt_voucher.jrxml, cmo_customer_invoice_report/report/cmo_sale_daybook.jrxml
แก้ไขชื่อตำแหน่งจาก Senior Accounting Manager เป็น Accounting Director
=> [FIX] Position name - change

cmo_account/models/account_invoice.py, cmo_account/views/account_invoice_view.xml, cmo_account/wizard/edit_desc.xml
หลังจากทำการ Upgrade module: cmo_account แล้วทำการ update this only ทำให้เกิดปัญหาดังกล่าว
แก้โค๊ดส่วนนี้เพื่อแก้ปัญหาดังกล่าว และแก้ปัญหาเรื่อง support
=> [8.0][FIX] edit_desc

cmo_account/models/account_invoice.py, cmo_account/models/account_voucher.py, cmo_account/views/account_view.xml, cmo_account/views/account_voucher_view.xml
ลองตั้งค่าใน Odoo แล้วไม่ได้ จึงแก้ใน Code นะครับ รบกวน ตรวจสอบด้วยนะครับจะได้เอาไป Test ใน MUSE ต่อ เพราะทดสอบที่เครื่องตัวเองไม่ได้ครับ
=> [FIX] number_preprint

cmo_sale_report/models/sale.py, cmo_sale_report/report/cmo_sale_order.jrxml, cmo_sale_report/report/cmo_sale_order_additional.jrxml, cmo_sale_report/report/cmo_sale_order_estimate.jrxml
เนื่องจาก user ไม่มีสิทธิ์เข้าถึง hr.job จึงเปลี่ยน uid ที่ context เป็น uid=1 เพราะรายงานทั้ง 4 รายงานไม่จำเป็นต้อง Print ข้อมูลของ uid 
รายงาน และ user ที่มีปัญหา หลังจากแก้ไข
=> [8.0][FIX] user_access

cmo_account/views/account_voucher_view.xml
=> [FIX] move_position_approver

cmo_customer_receipt_voucher_report/report/report_customer_receipt_voucher.py, cmo_customer_receipt_voucher_report/report/report_customer_receipt_voucher.xml, cmo_customer_receipt_voucher_report/wizards/customer_receipt_voucher.py, cmo_customer_receipt_voucher_report/wizards/customer_receipt_voucher_wizards.xml
สิ่งที่แก้
1.Transaction ดึง Name / Project Name
2. Wizard เพิ่ม Number Document และ Due Date
3. รายละเอียดธนาคารสามารถดึงจาก Bank Receipt
กรณี Customer Payment มี Bank Receipt
กรณี Customer Payment ไม่มี Bank Receipt
* NOTE: ผมไม่แน่ใจตรง Code ส่วนของการ Quary เลยครับไม่แน่ใจว่า มันดีหรือเปล่ารบกวนพี่ป๊อดดูให้ทีนะครับ ขอบคุณครับ
=> [FIX] customer_receipt_voucher_report

cmo_prq/models/purchase.py
แก้ไขเมื่อ ทำการ cancel PO แล้วให้ยกเลิก PRQ auto
ก่อน cancel PO
หลังจาก cancel PO
=> [FIX] reject prq after cancel po

cmo_account/models/account_voucher.py, cmo_account/views/account_voucher_view.xml, cmo_customer_invoice_report/report/cmo_supplier_payment_voucher.jrxml
=> [8.0][ADD] verify_by_id_2

cmo_account/report/withholding_cert.jrxml
https://github.com/ecosoft-odoo/cmo_generic/pull/89
จาก PR ที่แนบ ได้มีการเปลี่ยน type integer --> float 
จึงมาแก้ไขที่  pattern จาก pattern="#,##0 %" --> pattern="#,##0.00 %"
=> [FIX] Pattern in WHTC Form

cmo_async_process/cmo_action_asset_compute/reports/cmo_journal_voucher_group.jrxml
แก้ไขดึงข้อมูลผิดครับ
ที่หน้าดังกล่าวไม่มี field company_id
แก้โดยดึงชื่อ company จาก create_uid แทน
=> FIX - LOGO

cmo_sale_report/report/cmo_sale_order.jrxml
Edit cmo sale order report by adding tax.
cc. @newtratip
=> [8.0][ENH]cmo_sale_order

cmo_purchase_report/__init__.py, cmo_purchase_report/__openerp__.py, cmo_purchase_report/jrxml_reports/cmo_purchase_order.jrxml, cmo_purchase_report/jrxml_reports/cmo_purchase_order_product.jrxml, cmo_purchase_report/models/__init__.py, cmo_purchase_report/models/purchase_config.py, cmo_purchase_report/models/res_company.py, cmo_purchase_report/views/purchase_config_views.xml
Edit cmo_purchase_report by adding purchase_config.
cc. @newtratip
=> [8.0][ENH]cmo_purchase_report

muse_account_report/report/muse_customer_payment.jrxml, muse_account_report/report/muse_customer_payment_receipt_tax_invoice_peo.jrxml, muse_account_report/report/muse_receipt_tax_invoice_peo.jrxml
Edit account report's muse company 3 form include, customer payment, receipt tax and receipt tax peo.
cc. @newtratip
=> [8.0][ENH]muse_account_report

cmo_purchase_report/jrxml_reports/cmo_purchase_order.jrxml, cmo_purchase_report/jrxml_reports/cmo_purchase_order_product.jrxml
Edit purchase report by adjust font size.
cc. @newtratip
=> [8.0][ENH]purchase_report

cmo_sale_report/__openerp__.py, cmo_sale_report/models/sale.py, cmo_sale_report/report/cmo_sale_order.jrxml, cmo_sale_report/report/cmo_sale_order_additional.jrxml, cmo_sale_report/report/cmo_sale_order_estimate.jrxml, cmo_sale_report/views/sale_view.xml
Add field display operating unit. 
Display operating unit field is boolean and used to quotation form with operating unit field.
If this field active, operating unit show up to quotation form.
cc. @newtratip
=> [8.0][ADD]Field_display_operating_unit

cmo_account/models/account_invoice.py, cmo_account/wizard/edit_desc_wizard.py
Edit description in invoice line by added warning when the description is non-correct.
Edit description detail in invoice line. This description is name field in edit.desc module by added strip method when description is non-correct.
cc. @newtratip
=> [8.0][ENH]description in invoice line

cmo_account_report/reports/xlsx_report_asset.py
Enhance xlsx report asset by edit query to remove the condition is state != close and value_depreciated != 0.
Result, asset stage close is show in asset report.
cc. @newtratip
=> [8.0][ENH]cmo_account_report

cmo_account/views/account_view.xml
Enhance account view in cmo_account module by added account special view. This view is true in period special context  or closing period.
cc. @newtratip
=> [8.0][ADD]view_account_special

cmo_project/models/project.py
change condition check state SO to INV
=> [FIX] condition paid status project

cmo_customer_invoice_report/report/cmo_customer_refund.jrxml, cmo_customer_invoice_report/report/cmo_customer_refund_cr_tax.jrxml
On the credit note line show only others note detail.
Waiting the customer test, not merge yet.
cc: @ps-tubtim
=> [8.0][FIX] Credit Note and Credit Note/Tax Invoice

cmo_project/models/project.py
fix _compute_out_invoice_count and _compute_is_invoiced_and_paid 
due to cannot open some project documents.
=> [FIX] cmo_project: fix _compute_out_invoice_count

cmo_project/models/project.py
Fix some documents that cannot be opened by some accounts.
=> [FIX] cmo_project: _compute_price_and_cost

cmo_project/models/project.py
=> [8.0][FIX] cmo_project

cmo_delete_attachment/__init__.py, cmo_delete_attachment/__openerp__.py, cmo_delete_attachment/models/__init__.py, cmo_delete_attachment/models/ir_attachment.py
Add new module "cmo_delete_attachment"
This module allows users to delete their own attachments.
=> [ADD] cmo_delete_attachment

cmo_hr_level_validation/models/hr_level_validation.py
Fix approver cannot approve hr_expense
=> [FIX] approve_button

cmo_account_supplier_billing/views/account_invoice.xml
Add checkbox to Supplier Billing Items to make them be available for actions.
=> [FIX] supplier_billing_items: add checkbox

cmo_customer_invoice_report/report/cmo_receipt_backup.jrxml
Fix Printing Multi documents can print footer
=> [FIX] print_multi_document

cmo_customer_invoice_report/report/cmo_receipt.jrxml
FIX printing document : Receipt
=> [FIX] fix_print_document

cmo_account_supplier_billing/models/account_invoice.py, cmo_account_supplier_billing/models/supplier_billing.py
=> [8.0][FIX] cmo_account_supplier_billing

cmo_account_supplier_billing/models/supplier_billing.py, cmo_account_supplier_billing/views/account_invoice.xml, cmo_account_supplier_billing/views/supplier_billing.xml, cmo_customer_invoice_report/models/account.py, cmo_customer_invoice_report/report/cmo_supplier_billing.jrxml
Change report details
Change tree view items
Add logs
=> [FIX] cmo_supplier_billing
